### ISSUE TITLE
Migration from LinkedWiki to SPARQL

### ISSUE THREAD

**Issue by physikerwelt** [ProfessionalWiki/SPARQL#21]
LinkedWiki uses https://github.com/BorderCloud/SPARQL to get the SPARQL result. There, a type is generated.  

https://github.com/BorderCloud/SPARQL/blob/73915d86eb6d7859961934e87c2f325d368ad44d/src/ParserSparqlResult.php#L97

which can give useful information on how to display the results. Does this extension provide similar functionality?

As I was trying to use the extension from another extension, I was looking at https://github.com/ProfessionalWiki/SPARQL/blob/master/tests/integration/SparqlLuaQueryRunnerIntegrationTest.php to understand how I could use the SPARQL result in downstream applications.

**Comment by JeroenDeDauw** [comment]
Could you give an example of this type information that you receive via LinkedWiki?

For your extension, do you wish to use the PHP services provided by our SPARQL extension to talk to Blazegraph? The PHP Service we have ([SparqlLuaQueryRunner](https://github.com/ProfessionalWiki/SPARQL/blob/master/src/SparqlLuaQueryRunner.php)) is extremely thin: it makes an HTTP request to blazegraph, and then returns blazegraphs own result structure. If you need to run SPARQL queries in your own extension, you could use the same approach by copying over some lines from this extension. I don't see what you would gain by building on top of this extension.

**Comment by physikerwelt** [comment]
Yes, after looking at your code, that seems to be the best solution. Thank you for your very valuable hint here.
